# syntax=docker/dockerfile:1

FROM node:22-alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

ARG VITE_BASE_PATH=/
ARG VITE_KINOPOISK_API_KEY
ARG VITE_KINOPOISK_API_BASE_URL=https://kinopoiskapiunofficial.tech/api
ARG VITE_ALLOHA_TOKEN
ARG VITE_PLAYER_EMBED_DOMAIN=nayteruz.github.io
ARG VITE_ENABLE_ALLOHA=true
ARG VITE_HDVB_TOKEN
ARG VITE_PLAYER_TEMPLATES

ENV VITE_BASE_PATH=$VITE_BASE_PATH
ENV VITE_KINOPOISK_API_KEY=$VITE_KINOPOISK_API_KEY
ENV VITE_KINOPOISK_API_BASE_URL=$VITE_KINOPOISK_API_BASE_URL
ENV VITE_ALLOHA_TOKEN=$VITE_ALLOHA_TOKEN
ENV VITE_PLAYER_EMBED_DOMAIN=$VITE_PLAYER_EMBED_DOMAIN
ENV VITE_ENABLE_ALLOHA=$VITE_ENABLE_ALLOHA
ENV VITE_HDVB_TOKEN=$VITE_HDVB_TOKEN
ENV VITE_PLAYER_TEMPLATES=$VITE_PLAYER_TEMPLATES

RUN npm run build:selfhost

FROM nginx:1.27-alpine

COPY deploy/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
